LTO_ENABLE = yes

VIA_ENABLE = yes
POINTING_DEVICE_ENABLE = yes

ENCODER_ENABLE = no
OLED_ENABLE = no
RGB_MATRIX_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
COMBO_ENABLE = yes

UNICODE_COMMON = yes
UCIS_ENABLE = yes

CAPS_WORD_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
